#!/usr/bin/env bash
mkdir -p ../Output_Dir_Mine

arr=()
while IFS=$'\n' read -r line; 
  do
    arr+=($line)
  done < "../input.txt"


containsElement () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}


for fullfile in $(find $pwd -type f | sort -nr | cut -d: -f2- );
do
  filename=$(basename -- "$fullfile")
  extension="${filename##*.}"
  fname="${filename%.*}"
  
  #if extension not allowed,continue

  if [[ "$fname" == "$extension" ]]; #file has no extension
  then
      mkdir -p ../Output_Dir_Mine/Others
      cp $fullfile ../Output_Dir_Mine/Others
      if [ ! -e "../Output_Dir_Mine/Others/desc_others.txt" ] ; then
        touch "../Output_Dir_Mine/Others/desc_others.txt"
      fi
      echo "$fullfile" >> "../Output_Dir_Mine/Others/desc_others.txt"
      
  else
      mkdir -p ../Output_Dir_Mine/$extension
      cp $fullfile ../Output_Dir_Mine/$extension
      if [ ! -e "../Output_Dir_Mine/$extension/desc_${extension}.txt" ] ; then
        touch "../Output_Dir_Mine/$extension/desc_${extension}.txt"
        #append filepath
      fi
      echo "$fullfile" >> ../Output_Dir_Mine/$extension/desc_${extension}.txt
    
  fi

  
  
done