#!/usr/bin/env bash
mkdir -p ../Output_Dir_Mine

arr=()
while IFS=$'\n' read -r line; 
  do
    arr+=($line)
  done < "../input.txt"



declare -A dict

for fullfile in $(find $pwd -type f | sort -nr | cut -d: -f2- );
do
  filename=$(basename -- "$fullfile")
  extension="${filename##*.}"
  fname="${filename%.*}"
  
  #if extension not allowed,continue
  allowed=1
  for i in "${!arr[@]}"
  do 

    if [[ "${arr[i]}" == "*$extension*" ]]; then 
      echo "paisi"
      allowed=0
      break
    fi 
  done

  if [ $allowed -eq 0 ]; then
    continue
  fi 

  if [[ "$fname" == "$extension" ]]; #file has no extension
  then
      mkdir -p ../Output_Dir_Mine/Others
      cp $fullfile ../Output_Dir_Mine/Others
      if [ ! -e "../Output_Dir_Mine/Others/desc_others.txt" ] ; then
        touch "../Output_Dir_Mine/Others/desc_others.txt"
      fi
      #append filepath
      x=${PWD##*/} 
      y=${fullfile:1}
      echo "$x$y" >> "../Output_Dir_Mine/Others/desc_others.txt"
      
  else
      mkdir -p ../Output_Dir_Mine/$extension
      cp $fullfile ../Output_Dir_Mine/$extension
      if [ ! -e "../Output_Dir_Mine/$extension/desc_${extension}.txt" ] ; then
        touch "../Output_Dir_Mine/$extension/desc_${extension}.txt"
      fi
      #append filepath
      x=${PWD##*/} 
      y=${fullfile:1}
      
      echo "$x$y" >> ../Output_Dir_Mine/$extension/desc_${extension}.txt
    
  fi

  
  
done